image: nixpkgs/nix-flakes:latest

variables:
  NIX_PATH: nixpkgs=channel:nixos-unstable

stages:
  - release

include:
  - component: "gitlab.com/DeterminateSystems/flakehub-push/component@main"
    inputs:
      stage: "release"
      visibility: "unlisted"
      rolling: true

# update:
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"'
#   script:
#     # Install Nix
#     - |
#       if ! hash nix ; then
#         curl \
#           --proto '=https' --tlsv1.2 -sSf -L \
#           https://install.determinate.systems/nix | \
#           sh -s -- install linux --no-confirm --init none
#         . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
#       fi
#     - git config user.email "bot@lferraz.com"
#     - git config user.name "LFerraz Bot"
#     - "git remote add gitlab_origin https://oauth2:$COMMIT_TOKEN@gitlab.com/Fryuni/ZShutils.git"
#     - nix run nixpkgs#just update-flake
#     - nix run nixpkgs#just update-jetbrains
#     - nix run nixpkgs#just update-rustCrates
#     - "git push gitlab_origin HEAD:main -o ci.skip"

# build-system-notebook:
#   stage: build
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "schedule"
#       when: never
#     - when: on_success
#   cache:
#     - paths: [/nix/store]
#   variables:
#     CACHIX_CACHE_NAME: fryuni
#     CACHIX_AUTH_TOKEN: "$CACHIX_AUTH_TOKEN"
#   before_script:
#     - nix-channel --add https://nixos.org/channels/nixpkgs-unstable
#     - nix-channel --update
#     - nix-env --install --attr nixpkgs.cachix
#     - cachix use "$CACHIX_CACHE_NAME"
#   script:
#     - cachix watch-exec "$CACHIX_CACHE_NAME" -- nix build .#homeConfigurations.notebook.activationPackage

# build-home-notebook:
#   stage: build
#   # image: nixos/nix:2.3.12
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "schedule"
#       when: never
#     - when: on_success
#   cache:
#     - paths: [/nix/store]
#   variables:
#     CACHIX_CACHE_NAME: fryuni
#     CACHIX_AUTH_TOKEN: "$CACHIX_AUTH_TOKEN"
#   before_script:
#     - nix-channel --add https://nixos.org/channels/nixpkgs-unstable
#     - nix-channel --update
#     - nix-env --install --attr nixpkgs.cachix
#     - cachix use "$CACHIX_CACHE_NAME"
#   script:
#     - cachix watch-exec "$CACHIX_CACHE_NAME" -- nix build .#nixosConfigurations.notebook.config.system.build.toplevel
